"""
Convert a TFLite model to a C byte array for inclusion in Arduino sketches.

Usage
─────
  python to_c_array.py                         # converts tiny_cnn_int8.tflite
  python to_c_array.py --model my_model.tflite --out model_data.h

Output
──────
  A C header file containing:
    const unsigned char g_model_data[] = { 0x18, 0x00, ... };
    const unsigned int  g_model_data_len = 12345;

  Include it in your Arduino sketch alongside the TFLite Micro library:
    #include "model_data.h"
    #include "tensorflow/lite/micro/all_ops_resolver.h"
    ...
    const tflite::Model* model = tflite::GetModel(g_model_data);

Arduino Nano 33 BLE note
────────────────────────
  The nRF52840 has 1 MB flash.  After including the TFLite Micro library
  (~200 kB) and the sketch overhead, you have ~600 kB free for the model.
  tiny_cnn_int8.tflite is ~134 kB, leaving ample headroom.

  Tensor arena (RAM) estimate for this model:
    Input buffer  :  96×96×3 = 27 648 bytes
    Activations   : ~30 kB  (largest intermediate feature map: 12×12×256 = 36 864)
    Scratch       : ~4 kB
    Total          : ~60–80 kB  (well within the 256 kB RAM limit)
"""

import argparse
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))


def tflite_to_c_array(tflite_path: str, out_path: str, var_name: str = "g_model_data") -> None:
    with open(tflite_path, "rb") as f:
        data = f.read()

    size = len(data)
    hex_values = ", ".join(f"0x{b:02x}" for b in data)

    # Wrap at 12 values per line for readability
    chunks = [hex_values[i:i + 12*6] for i in range(0, len(hex_values), 12*6)]
    formatted = ",\n  ".join(chunks)

    header = f"""\
// Auto-generated by to_c_array.py
// Source: {os.path.basename(tflite_path)}
// Size  : {size:,} bytes ({size / 1024:.1f} kB)
//
// Include this file in your Arduino sketch and initialise TFLite Micro:
//
//   #include "{os.path.basename(out_path)}"
//   #include "tensorflow/lite/micro/all_ops_resolver.h"
//   #include "tensorflow/lite/micro/micro_interpreter.h"
//   #include "tensorflow/lite/schema/schema_generated.h"
//
//   const int kTensorArenaSize = 80 * 1024;  // 80 kB should be sufficient
//   uint8_t tensor_arena[kTensorArenaSize];
//
//   const tflite::Model* model = tflite::GetModel({var_name});
//   tflite::AllOpsResolver resolver;
//   tflite::MicroInterpreter interpreter(model, resolver, tensor_arena,
//                                        kTensorArenaSize);
//   interpreter.AllocateTensors();
//
// Input tensor (INT8): shape [1, {96}, {96}, 3]
// Output tensor (INT8): shape [1, 3]  — indices: 0=fire, 1=other, 2=smoke
// De-quantise output: float_score = (int8_val - zero_point) * scale

#pragma once
#include <stdint.h>

alignas(8) const uint8_t {var_name}[] = {{
  {formatted}
}};
const unsigned int {var_name}_len = {size}U;
"""

    with open(out_path, "w") as f:
        f.write(header)

    print(f"Written: {out_path}")
    print(f"  Array variable : {var_name}[{size:,}]")
    print(f"  Size           : {size / 1024:.1f} kB")


def parse_args():
    p = argparse.ArgumentParser(
        description="Convert TFLite model to Arduino-compatible C header"
    )
    p.add_argument("--model", default=os.path.join(_HERE, "tiny_cnn_int8.tflite"),
                   help="Input .tflite file")
    p.add_argument("--out", default=os.path.join(_HERE, "model_data.h"),
                   help="Output C header file path")
    p.add_argument("--var-name", default="g_model_data",
                   help="Name of the C byte-array variable")
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()

    if not os.path.exists(args.model):
        sys.exit(f"[ERROR] Model not found: {args.model}\n"
                 "Run export.py first to generate tiny_cnn_int8.tflite.")

    tflite_to_c_array(args.model, args.out, args.var_name)
    print("\nNext: copy model_data.h into your Arduino sketch folder and "
          "link against the TFLite Micro library.")
